/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


package labproject;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author mddilshad
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    
    JButton alogout=new JButton("Logout"); 
    JButton logout=new JButton("Logout");
    JButton post = new JButton("Post");
    BufferedImage amyPictures = null; 
    BufferedImage myPictures = null;

    JFrame AdminForm;
    JPanel amainPanel,anotificationAndInfoPanel,aphotoHolderPanel,alogoutPanel;
    JLabel aphotoHolder;
    JTable t;
    JTextArea anotice;
    
    JFrame mainPanelHolerForm;
    JPanel mainPanel,notificationAndInfoPanel,photoHolderPanel,logoutPanel; 
    JLabel photoHolder;
    JScrollPane scroller;
    
    
    public LoginForm() {
        initComponents();
        this.setLocationRelativeTo(null);//Added by stackoverflow
        this.setTitle("Log In Form");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(17, 11, 88));
        jLabel1.setText("Hostel Mangement Software");

        jCheckBox1.setText("Admin");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                itemStateChangedActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Email:");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("Password:");

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(40, 13, 228));
        jLabel4.setText("if you are new click here");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(139, 139, 139)
                                    .addComponent(jCheckBox1))
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jButton1)))
                .addGap(0, 31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addComponent(jCheckBox1)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(44, 44, 44)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        System.out.println("hi");
        FormFlow.switchForward(new NewCustomer());
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean r;
        r = false;
        if(jCheckBox1.isSelected() == false){ // means he or she is a custmer.
            r = new DBConn().customerLoginCheck(jTextField2.getText(),jPasswordField1.getText());
            if(r == false){
                JOptionPane.showMessageDialog(this,"Log in failed");
            }
            System.out.println(r);
            if(r == true){
                String s;
                String n;
                String em;
                String ad;
                s = new DBConn().customerPicLocation(jTextField2.getText(),jPasswordField1.getText());
                n = new DBConn().getCustomerName(jTextField2.getText(),jPasswordField1.getText());
                em = new DBConn().getCustomerEmail(jTextField2.getText(),jPasswordField1.getText());
                ad = new DBConn().getCustomerDate(jTextField2.getText(),jPasswordField1.getText());
                try {
                    System.out.println(s);
                    myPictures = ImageIO.read(new File(s));
                } catch (IOException ex) {
                    System.out.println("can not read image");
                    Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
                
                
                mainPanelHolerForm = new JFrame();
                mainPanel = new JPanel();
                notificationAndInfoPanel = new JPanel();
                photoHolderPanel = new JPanel();
                logoutPanel = new JPanel();
                photoHolder = new JLabel(new ImageIcon(myPictures));
                scroller = new JScrollPane(notificationAndInfoPanel);
                
                notificationAndInfoPanel.setLayout(new BoxLayout(notificationAndInfoPanel,BoxLayout.Y_AXIS));
                notificationAndInfoPanel.setBackground(Color.lightGray);
                notificationAndInfoPanel.setBorder(new EmptyBorder(10,10,10,10));
                /**Adding stuff in notification panel**/
                notificationAndInfoPanel.add(new JLabel("############  Notices ################"));
                notificationAndInfoPanel.add(new JLabel("\n\n\n"));
                new DBConn().viewNotices(notificationAndInfoPanel);
                notificationAndInfoPanel.add(Box.createVerticalGlue());
                /**Adding stuff in notification panel ends**/
                
                photoHolderPanel.setLayout(new BoxLayout(photoHolderPanel,BoxLayout.Y_AXIS));
                photoHolderPanel.setBorder(new EmptyBorder(10,10,10,10));
                photoHolderPanel.add(photoHolder);
                photoHolderPanel.add(new JLabel("\n\n"+"Name: "+n));
                photoHolderPanel.add(new JLabel("\n"+"Gmail: "+em));
                photoHolderPanel.add(new JLabel("\n"+"Admitted on: "+ad));
                
                logoutPanel.setBorder(new EmptyBorder(2,2,2,2));
                logoutPanel.add(logout);
                logout.addActionListener(new ActionListener() { 
                   
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        //To change body of generated methods, choose Tools | Templates.
                        
                        FormFlow.switchBackward();
                    }
                  } );
                
                mainPanel.setLayout(new BorderLayout());
		mainPanel.add(logoutPanel,BorderLayout.SOUTH); 
		mainPanel.add(photoHolderPanel,BorderLayout.WEST);
                mainPanel.add(scroller,BorderLayout.CENTER);

                mainPanelHolerForm.add(mainPanel);
                mainPanelHolerForm.setSize(900,700);
                mainPanelHolerForm.setLocationRelativeTo(null);//Added by stackoverflow
                mainPanelHolerForm.setTitle("Customer Info and Notice Board");
                FormFlow.switchForward(mainPanelHolerForm);
                
                
            }
        }
        else if(jCheckBox1.isSelected() == true){
            r = new DBConn().adminLoginCheck(jTextField2.getText(),jPasswordField1.getText());
            if(r == false){
                JOptionPane.showMessageDialog(this,"Log in failed");
            }
            if(r == true){
                //JOptionPane.showMessageDialog(null, "Successfull Admin login.Soon we will add a Admin page.So that Admin call alter tables and delete customers");
                AdminForm = new JFrame();
                amainPanel = new JPanel();
                anotificationAndInfoPanel = new JPanel();
                aphotoHolderPanel = new JPanel();
                alogoutPanel = new JPanel();
                scroller = new JScrollPane(aphotoHolderPanel);
                anotice = new JTextArea(30,30);
                
                final JPanel txtarea = new JPanel();
                txtarea.setMaximumSize(new Dimension(400,400));
                //txtarea.setBorder(new EmptyBorder(5,5,5,5));
                txtarea.setAlignmentX( Component.LEFT_ALIGNMENT );//0.0
                
                aphotoHolderPanel.setLayout(new BoxLayout(aphotoHolderPanel,BoxLayout.Y_AXIS));
                aphotoHolderPanel.setBorder(new EmptyBorder(10,10,10,10));
                aphotoHolderPanel.add(new JLabel("###   Customer  Info   ###"));
                
                anotificationAndInfoPanel.setLayout(new BoxLayout(anotificationAndInfoPanel,BoxLayout.Y_AXIS));
                anotificationAndInfoPanel.setBackground(Color.LIGHT_GRAY);
                anotificationAndInfoPanel.setBorder(new EmptyBorder(10,10,10,10));
                
                t = new DBConn().addCustomerRowsInAdmin();
                anotificationAndInfoPanel.add(new JLabel("Customer Table"));
                anotificationAndInfoPanel.add(t);
                t.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
                    
                    public void valueChanged(ListSelectionEvent event){
                        //aphotoHolderPanel.add(new JLabel(t.getValueAt(t.getSelectedRow(), 0).toString()));
                        if (!event.getValueIsAdjusting()) {
                            try {
                                //This line prevents double events
                                amyPictures = ImageIO.read(new File(t.getValueAt(t.getSelectedRow(), 2).toString()));
                            } catch (IOException ex) {
                                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            aphotoHolder = new JLabel(new ImageIcon(amyPictures));
                            aphotoHolderPanel.add( aphotoHolder);
                            aphotoHolderPanel.add(new JLabel("\n"));
                            aphotoHolderPanel.add(new JLabel("Name : "+ t.getValueAt(t.getSelectedRow(), 0).toString()));
                            aphotoHolderPanel.add(new JLabel("Email : "+ t.getValueAt(t.getSelectedRow(), 1).toString()));
                            
                            
                            JButton del = new JButton("Delete");
                            aphotoHolderPanel.add(del);
                            del.addActionListener(new ActionListener() { 
                                @Override
                                public void actionPerformed(ActionEvent e) {
                                    //To change body of generated methods, choose Tools | Templates.
                                    t.revalidate();
                                    aphotoHolderPanel.revalidate();
                                    new DBConn().deleteCustomer(t.getValueAt(t.getSelectedRow(), 0).toString(),t.getValueAt(t.getSelectedRow(), 1).toString());
                                    JOptionPane.showMessageDialog(AdminForm,"Customer deleted.Log in Again to see Updated view.");
                                }
                              } );
                            
                            aphotoHolderPanel.revalidate();
                            t.revalidate();
                            aphotoHolderPanel.add(new JLabel("\n\n--------------\n\n"));
                            aphotoHolderPanel.add(new JLabel("\n\n"));
                        }
                    }
                });
                anotificationAndInfoPanel.add(Box.createVerticalStrut(50));
                anotificationAndInfoPanel.add( Box.createHorizontalGlue() );
                anotificationAndInfoPanel.add( new JLabel("Post a announcement here: "));
                txtarea.add(anotice);
                anotificationAndInfoPanel.add(txtarea);
                anotificationAndInfoPanel.add(post);
                JButton clearNotices = new JButton("Clear Notices");
                clearNotices.addActionListener(new ActionListener() { 
                   
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        //To change body of generated methods, choose Tools | Templates.
                        new DBConn().clearNotices();
                        JOptionPane.showMessageDialog(AdminForm,"Notification page of customer been cleared");
                    }
                  } );
                post.addActionListener(new ActionListener() { 
                   
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        //To change body of generated methods, choose Tools | Templates.
                        new DBConn().insertIntoNotice(anotice.getText());
                        JOptionPane.showMessageDialog(AdminForm,"Notification been posted.");
                        notificationAndInfoPanel.revalidate();//whenever new notices are published.
                    }
                  } );
                anotificationAndInfoPanel.add(clearNotices);
                
                
                
                
                
                alogoutPanel.setBorder(new EmptyBorder(2,2,2,2));
                alogoutPanel.add(alogout);
                alogout.addActionListener(new ActionListener() { 
                   
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        //To change body of generated methods, choose Tools | Templates.
                        FormFlow.switchBackward();
                    }
                  } );
                
                amainPanel.setLayout(new BorderLayout());
		amainPanel.add(alogoutPanel,BorderLayout.SOUTH);
                amainPanel.add(anotificationAndInfoPanel,BorderLayout.CENTER);
                amainPanel.add(scroller,BorderLayout.WEST);
                
                AdminForm.add(amainPanel);
                AdminForm.setSize(900,900);
                AdminForm.setLocationRelativeTo(null);//Added by stackoverflow
                AdminForm.setTitle("Admin Form");
                FormFlow.switchForward(AdminForm);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Sorry no record in the database.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void itemStateChangedActionPerformed(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_itemStateChangedActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected() == true){
            jLabel2.setText("Admin_Id : ");
        }
        else{
            jLabel2.setText("Email: ");
        }
    }//GEN-LAST:event_itemStateChangedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
